-- Rollback for 20260503000000_init
-- See AGENTS/database/03-rollback-runbook.md.

DROP TABLE IF EXISTS "RefreshToken" CASCADE;
DROP TABLE IF EXISTS "OneTimeToken" CASCADE;
DROP TABLE IF EXISTS "Session" CASCADE;
DROP TABLE IF EXISTS "AccountProvider" CASCADE;
DROP TABLE IF EXISTS "RolePermission" CASCADE;
DROP TABLE IF EXISTS "UserRole" CASCADE;
DROP TABLE IF EXISTS "Permission" CASCADE;
DROP TABLE IF EXISTS "Role" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
